
spring.cloud.consul.host=47.115.214.28
spring.cloud.consul.port=8501

spring.cloud.consul.discovery.register=false
spring.cloud.gateway.discovery.locator.enabled=false
spring.cloud.consul.discovery.instance-id=gateway
server.port = 8083
service_name=test