name: Build and Package

on:
  push:
    branches:
    - master

jobs:
  build-and-package:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        project:
          - log_client
          - log_manager
    steps:
    
    - name: Set up JDK 8
      uses: actions/setup-java@v1
      with:
        java-version: '8'
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Build with Maven
      run: mvn -f ${{ matrix.project }}/pom.xml clean package
      
    # 将打包好的 Jar 包 放到 staging 文件夹
    - run: mkdir staging && cp ${{ matrix.project }}/target/*.jar staging
   
    - name: Set Release version env variable
      run: |
        cd ${{ matrix.project }}
        mvn -q -Dexec.executable="echo" -Dexec.args='${project.version}' --non-recursive exec:exec
        echo "RELEASE_VERSION=$(mvn -q -Dexec.executable=\"echo\" -Dexec.args=\'${project.version}\' --non-recursive exec:exec)" >> $GITHUB_ENV
    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "${{ env.RELEASE_VERSION }}"
        prerelease: false
        title: "${{ matrix.project }} ${{ env.RELEASE_VERSION }}"
        files: |
          staging/*.jar


